import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://byiuaepsgxyjorttumfw.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aXVhZXBzZ3h5am9ydHR1bWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyMjM2NzUsImV4cCI6MjAyODc5OTY3NX0.2GnYSwpiaYux_hIYnSNeFbGWSIYlho2GCxsDnjyWuMU')